repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "fe7a5361087093b5184460da13e0c56cf37154f4"
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/hakancelik96/unimport
      rev: 73e9054125d36a16caeffefd1049a83035ccfbf3
      hooks:
          - id: unimport
            args: [--remove, --include-star-import]
    - repo: https://github.com/pycqa/isort
      rev: "98673ff4bc158fdc79f587775b6a15abd9fdc248"
      hooks:
          - id: isort
            files: "litho/.*"
            args: ["--profile", "black", "--filter-files"]

    - repo: https://github.com/psf/black
      rev: "8a84bebcfcabddfd5b82a8cff0b830a745999b6c"
      hooks:
          - id: black

    - repo: https://gitlab.com/pycqa/flake8
      rev: "21d3c70d676007470908d39b73f0521d39b3b997"
      hooks:
          - id: flake8

    - repo: https://github.com/kynan/nbstripout
      rev: 9e7e0380da05bd6e8c58b50c3f3a2119e7dce13a
      hooks:
          - id: nbstripout
            files: ".ipynb"

    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: ""
    #   hooks:
    #       - id: mypy
    #         exclude: ^(docs/|example-plugin/|tests/fixtures)
    # - repo: https://github.com/pycqa/pydocstyle
    #   rev: ""
    #   hooks:
    #       - id: pydocstyle
